-- Active: 1692852423905@@127.0.0.1@3306@CMS

SHOW VARIABLES LIKE 'hostname'

SHOW VARIABLES LIKE 'port';

USE CMS

-- CREATING TABLES

CREATE TABLE EMPLOYEES (EMPLOYEE_ID VARCHAR(50), DOB VARCHAR(20), DOJ VARCHAR(50), DEPARTMENT_ID VARCHAR(50))

load data infile 'C://ProgramData//MySQL//MySQL Server 8.0//Uploads//Employee_Information.csv'
into table EMPLOYEES 
fields terminated by ','
lines terminated by '\n' 
ignore 1 lines

CREATE TABLE DEPARTMENTS (DEPARTMENT_ID VARCHAR(50), DEPARTMENT_NAME VARCHAR(200), DOE VARCHAR(50))

load data infile 'C://ProgramData//MySQL//MySQL Server 8.0//Uploads//Department_Information.csv'
into table DEPARTMENTS 
fields terminated by ','
lines terminated by '\n' 
ignore 1 lines

CREATE TABLE PERFORMANCE (STUDENT_ID VARCHAR(50) NOT NULL, SEMESTER_NAME VARCHAR(50), PAPER_ID VARCHAR(50), PAPER_NAME VARCHAR(50), MARKS INT NOT NULL)

load data infile 'C://ProgramData//MySQL//MySQL Server 8.0//Uploads//Student_Performance_Data.csv'
into table PERFORMANCE 
fields terminated by ','
lines terminated by '\n' 
ignore 1 lines

CREATE TABLE COUNCELING (STUDENT_ID VARCHAR(50), DOA VARCHAR(50), DOB VARCHAR(50), DEPARTMENT_CHOICE VARCHAR(50), DEPARTMENT_ADMISSION VARCHAR(50))

load data infile 'C://ProgramData//MySQL//MySQL Server 8.0//Uploads//Student_Counceling_Information.csv'
into table COUNCELING
fields terminated by ','
lines terminated by '\n' 
ignore 1 lines

CREATE TABLE PASSES (STUDENT_ID TEXT, 
                    PASS_TYPE TEXT, REASON TEXT, 
                    PAF_DATE DATE, PAT_DATE DATE, PAF_TIME TEXT, 
                    PAT_TIME TEXT, APPROVAL_STATUS TEXT,
                    USE_STATUS TEXT, OUT_TIME TEXT, IN_TIME TEXT)

load data infile 'C://ProgramData//MySQL//MySQL Server 8.0//Uploads//GatePassInformation.csv'
into table PASSES
fields terminated by ','
lines terminated by '\n' 
ignore 1 lines

DROP TABLE PASSES

CREATE TABLE SUSPENSION (STUDENT_ID TEXT, SSD DATE, SED DATE, REASON TEXT)

load data infile 'C://ProgramData//MySQL//MySQL Server 8.0//Uploads//Suspension_Information.csv'
into table SUSPENSION
fields terminated by ','
lines terminated by '\n' 
ignore 1 lines

CREATE TABLE ATTENDANCE (STUDENT_ID TEXT, A INT, 
                        B INT, C INT, D INT,
                        E INT, F INT, G INT)

load data infile 'C://ProgramData//MySQL//MySQL Server 8.0//Uploads//Attendance_Information.csv'
into table ATTENDANCE
fields terminated by ','
lines terminated by '\n' 
ignore 1 lines

CREATE TABLE TOTCLASS (PAPER_ID TEXT, TOTAL_CLASSES INT, CLASS_ID TEXT)

load data infile 'C://ProgramData//MySQL//MySQL Server 8.0//Uploads//TotalClassInformation.csv'
into table TOTCLASS
fields terminated by ','
lines terminated by '\n' 
ignore 1 lines

UPDATE TOTCLASS
SET CLASS_ID = SUBSTRING(CLASS_ID, 1,1)

SELECT * FROM TOTCLASS

-- PRE PROCESSING THE DATA

UPDATE COUNCELING SET DOA = SUBSTRING(DOA, 1, 10), DOB = SUBSTRING(DOB, 1, 10)

ALTER TABLE COUNCELING
MODIFY COLUMN DOA DATE;

ALTER TABLE COUNCELING
MODIFY COLUMN DOB DATE;

UPDATE DEPARTMENTS SET DOE = SUBSTRING(DOE, 1, 10)

UPDATE EMPLOYEES SET DEPARTMENT_ID = SUBSTRING(DEPARTMENT_ID, 1, 9)

ALTER TABLE DEPARTMENTS
MODIFY COLUMN DOE DATE;

UPDATE EMPLOYEES SET DOJ = SUBSTRING(DOJ, 1, 10), DOB = SUBSTRING(DOB, 1, 10)

ALTER TABLE EMPLOYEES
MODIFY COLUMN DOJ DATE;

ALTER TABLE EMPLOYEES
MODIFY COLUMN DOB DATE;

-- NORMALIZING THE TABLE PERFORMANCES

CREATE TABLE PAPERS AS
SELECT DISTINCT PAPER_ID, PAPER_NAME, SEMESTER_NAME
FROM PERFORMANCE;

ALTER TABLE PAPERS
ADD PRIMARY KEY (PAPER_ID);

CREATE TABLE MARKS (
    STUDENT_ID VARCHAR(50), 
    PAPER_ID VARCHAR(50), 
    MARKS INT,
    PRIMARY KEY (STUDENT_ID, PAPER_ID),
    FOREIGN KEY (PAPER_ID) REFERENCES PAPERS(PAPER_ID))

INSERT INTO MARKS (STUDENT_ID, PAPER_ID, MARKS)
SELECT DISTINCT STUDENT_ID, PAPER_ID, MARKS
FROM PERFORMANCE

-- SETTING PRIMARY KEYS FOR EACH TABLE

SHOW TABLES

CREATE TABLE COUNCELING_INFO AS
SELECT STUDENT_ID, DOA, DOB, DEPARTMENT_ADMISSION,
    GROUP_CONCAT(DISTINCT DEPARTMENT_CHOICE ORDER BY DEPARTMENT_CHOICE) AS DEPARTMENT_CHOICES
FROM COUNCELING
GROUP BY STUDENT_ID, DOA, DOB, DEPARTMENT_ADMISSION;

ALTER TABLE COUNCELING_INFO
ADD PRIMARY KEY (STUDENT_ID)

ALTER TABLE DEPARTMENTS
ADD PRIMARY KEY (DEPARTMENT_ID)

ALTER TABLE EMPLOYEES
ADD PRIMARY KEY (EMPLOYEE_ID, DEPARTMENT_ID)

UPDATE COUNCELING_INFO SET DEPARTMENT_ADMISSION = SUBSTRING(DEPARTMENT_ADMISSION, 1, 9)


-- FINAL (PROCESSED) TABLES

SELECT * FROM DEPARTMENTS

SELECT * FROM EMPLOYEES

SELECT * FROM MARKS

SELECT * FROM PAPERS

SELECT * FROM COUNCELING_INFO